In [83]:
# https://likegeeks.com/python-image-processing/

# Rotate an Image

In [1]:
import cv2

img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\fish.jpg')
img

array([[[ 99,  46,   3],
        [ 98,  45,   2],
        [ 98,  45,   2],
        ...,
        [208, 146,  32],
        [210, 147,  33],
        [211, 148,  34]],

       [[ 99,  45,   4],
        [101,  45,   4],
        [101,  45,   4],
        ...,
        [207, 145,  31],
        [209, 146,  32],
        [210, 147,  33]],

       [[103,  44,   4],
        [103,  44,   4],
        [103,  44,   4],
        ...,
        [209, 146,  32],
        [209, 146,  32],
        [209, 146,  32]],

       ...,

       [[ 92,  77,   8],
        [ 93,  77,   8],
        [ 93,  78,   6],
        ...,
        [164, 124,  59],
        [166, 126,  61],
        [166, 126,  61]],

       [[ 90,  75,   3],
        [ 95,  77,   6],
        [ 96,  78,   7],
        ...,
        [165, 124,  51],
        [165, 125,  53],
        [164, 124,  52]],

       [[ 90,  75,   3],
        [ 95,  77,   6],
        [ 96,  78,   7],
        ...,
        [165, 124,  51],
        [164, 124,  52],
        [164, 124,  52]]

In [2]:
type(img)

numpy.ndarray

In [3]:
# cv2.imshow('Original Image', img)
# cv2.waitKey(0)

In [4]:
img.shape

(698, 920, 3)

In [5]:
height, width = img.shape[0:2]
img.shape[0:2]

(698, 920)

In [6]:
rotationMatrix = cv2.getRotationMatrix2D((width/2, height/2), 45, .5)
rotationMatrix

array([[ 3.53553391e-01,  3.53553391e-01,  1.73975307e+02],
       [-3.53553391e-01,  3.53553391e-01,  3.88244426e+02]])

In [7]:
rotatedImage = cv2.warpAffine(img, rotationMatrix, (width, height))
rotatedImage

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [8]:
# cv2.imshow('Original Image', img)
# cv2.imshow('Rotated Image', rotatedImage)

# cv2.waitKey(0)

# Crop an Image

In [9]:
startRow = int(height*.15)
startCol = int(width*.15)
endRow = int(height*.85)
endCol = int(width*.85)

startRow, startCol, endRow, endCol

(104, 138, 593, 782)

In [10]:
croppedImage = img[startRow:endRow, startCol:endCol]
croppedImage

array([[[211, 113,  11],
        [208, 113,  10],
        [207, 112,   9],
        ...,
        [233, 164,  47],
        [233, 164,  47],
        [236, 166,  52]],

       [[210, 112,  10],
        [208, 113,  10],
        [206, 111,   8],
        ...,
        [232, 163,  46],
        [233, 164,  47],
        [236, 166,  52]],

       [[210, 112,  10],
        [207, 112,   9],
        [206, 111,   8],
        ...,
        [233, 164,  47],
        [234, 165,  48],
        [237, 167,  53]],

       ...,

       [[ 31,  48,   5],
        [ 28,  47,   4],
        [ 27,  46,   3],
        ...,
        [163, 108,   4],
        [168, 110,   5],
        [173, 113,   7]],

       [[ 32,  49,   6],
        [ 31,  48,   5],
        [ 27,  46,   3],
        ...,
        [163, 108,   3],
        [167, 109,   4],
        [174, 112,   6]],

       [[ 32,  46,   4],
        [ 30,  47,   4],
        [ 29,  46,   3],
        ...,
        [168, 110,   5],
        [170, 108,   2],
        [171, 105,   0]]

In [11]:
# cv2.imshow('Original Image', img)
# cv2.imshow('Cropped Image', croppedImage)

# cv2.waitKey(0)

# Resize an Image

In [12]:
newImg = cv2.resize(img, (width, height), fx=0.75, fy=0.75)
newImg

array([[[ 99,  46,   3],
        [ 98,  45,   2],
        [ 98,  45,   2],
        ...,
        [208, 146,  32],
        [210, 147,  33],
        [211, 148,  34]],

       [[ 99,  45,   4],
        [101,  45,   4],
        [101,  45,   4],
        ...,
        [207, 145,  31],
        [209, 146,  32],
        [210, 147,  33]],

       [[103,  44,   4],
        [103,  44,   4],
        [103,  44,   4],
        ...,
        [209, 146,  32],
        [209, 146,  32],
        [209, 146,  32]],

       ...,

       [[ 92,  77,   8],
        [ 93,  77,   8],
        [ 93,  78,   6],
        ...,
        [164, 124,  59],
        [166, 126,  61],
        [166, 126,  61]],

       [[ 90,  75,   3],
        [ 95,  77,   6],
        [ 96,  78,   7],
        ...,
        [165, 124,  51],
        [165, 125,  53],
        [164, 124,  52]],

       [[ 90,  75,   3],
        [ 95,  77,   6],
        [ 96,  78,   7],
        ...,
        [165, 124,  51],
        [164, 124,  52],
        [164, 124,  52]]

In [13]:
# cv2.imshow('Original Image', img)
# cv2.imshow('Resized Image', newImg)
# cv2.waitKey(0)

# Adjust Image Contrast

cv2.addWeighted(source_img1, alpha1, source_img2, alpha2, beta)


In [85]:
import numpy as np

img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\fish.jpg')
img1 = np.zeros(img.shape, img.dtype)

contrast_img = cv2.addWeighted(img, 2.5, img1, 0, 0)
contrast_img

array([[[248, 115,   8],
        [245, 112,   5],
        [245, 112,   5],
        ...,
        [255, 255,  80],
        [255, 255,  82],
        [255, 255,  85]],

       [[248, 112,  10],
        [252, 112,  10],
        [252, 112,  10],
        ...,
        [255, 255,  78],
        [255, 255,  80],
        [255, 255,  82]],

       [[255, 110,  10],
        [255, 110,  10],
        [255, 110,  10],
        ...,
        [255, 255,  80],
        [255, 255,  80],
        [255, 255,  80]],

       ...,

       [[230, 192,  20],
        [232, 192,  20],
        [232, 195,  15],
        ...,
        [255, 255, 148],
        [255, 255, 152],
        [255, 255, 152]],

       [[225, 188,   8],
        [238, 192,  15],
        [240, 195,  18],
        ...,
        [255, 255, 128],
        [255, 255, 132],
        [255, 255, 130]],

       [[225, 188,   8],
        [238, 192,  15],
        [240, 195,  18],
        ...,
        [255, 255, 128],
        [255, 255, 130],
        [255, 255, 130]]

In [87]:
# cv2.imshow('Original Image', img)
# cv2.imshow('Contrast Image', contrast_img)

# cv2.waitKey(0)

In [88]:
cv2.addWeighted, np.zeros, img.shape, img.dtype

(<function addWeighted>, <function numpy.zeros>, (698, 920, 3), dtype('uint8'))

# Make an image blurry

### Gaussian Blur

In [89]:
blur_image = cv2.GaussianBlur(img, (7,7), 0)
blur_image

array([[[101,  45,   3],
        [101,  45,   3],
        [101,  45,   3],
        ...,
        [209, 146,  33],
        [209, 146,  32],
        [209, 146,  32]],

       [[101,  45,   4],
        [101,  45,   4],
        [102,  44,   3],
        ...,
        [209, 146,  33],
        [209, 146,  32],
        [209, 146,  32]],

       [[103,  44,   4],
        [103,  44,   4],
        [103,  44,   4],
        ...,
        [209, 146,  32],
        [209, 146,  32],
        [209, 146,  32]],

       ...,

       [[ 94,  77,   6],
        [ 94,  77,   6],
        [ 94,  77,   6],
        ...,
        [164, 124,  56],
        [164, 125,  57],
        [164, 125,  57]],

       [[ 94,  77,   6],
        [ 94,  77,   6],
        [ 94,  77,   6],
        ...,
        [164, 124,  53],
        [164, 124,  55],
        [165, 125,  55]],

       [[ 94,  77,   6],
        [ 94,  77,   6],
        [ 95,  77,   6],
        ...,
        [164, 124,  53],
        [164, 124,  54],
        [165, 124,  54]]

In [90]:
# cv2.imshow('Original Image', img)
# cv2.imshow('Gaussian Blur Image', blur_image)

# cv2.waitKey(0)

### Median Blur

In [179]:
img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\10-Median-Blur.png', 0)

height, width = img.shape[0:2]
startRow = int(height/16)
startCol = int(width*0)
endRow = int(height*1)
endCol = int(width*.5)
croppedImage = img[startRow:endRow, startCol:endCol]

blur_image = cv2.medianBlur(croppedImage,5)
blur_image

array([[138, 170, 213, ..., 150,  33,  33],
       [138, 198, 218, ..., 150,  33,  33],
       [138, 203, 226, ..., 150,  33,  33],
       ...,
       [138, 194, 207, ..., 150,  52,  52],
       [138, 174, 195, ..., 150,  52,  52],
       [138, 174, 195, ..., 150,  52,  52]], dtype=uint8)

In [180]:
# cv2.imshow('Original Image', croppedImage)
# cv2.imshow('Median Blur Image', blur_image)
# cv2.waitKey(0)

-1

# Detect Edges

In [93]:
import cv2
img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\status.png', 1)
# img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\10-Median-Blur.png')

height, width = img.shape[0:2]
edge_img = cv2.Canny(img, width, height)
edge_img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [94]:
# cv2.imshow('Original Image', img)
# cv2.imshow("Detected Edges", edge_img)

# cv2.waitKey(0)

-1

# Convert image to grayscale (Black & White)

In [140]:
img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\fish.jpg')
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray_img

array([[ 39,  38,  38, ..., 119, 120, 121],
       [ 39,  39,  39, ..., 118, 119, 120],
       [ 39,  39,  39, ..., 119, 119, 119],
       ...,
       [ 58,  58,  58, ..., 109, 111, 111],
       [ 55,  58,  59, ..., 107, 108, 107],
       [ 55,  58,  59, ..., 107, 107, 107]], dtype=uint8)

In [137]:
# cv2.imshow("Original Image", img)
# cv2.imshow("Gray Scale Image", gray_img)

# cv2.waitKey(0)

-1

# Centroid (Center of blob) detection

In [155]:
import cv2

img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\py.jpg')
# cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray_img

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [156]:
moment = cv2.moments(gray_img)
type(moment), moment

(dict,
 {'m00': 95823144.0,
  'm10': 30600929028.0,
  'm01': 30984955081.0,
  'm20': 13122412500470.0,
  'm11': 9894963465709.0,
  'm02': 13456069241041.0,
  'm30': 6330764666097420.0,
  'm21': 4243261798827825.0,
  'm12': 4297196641149427.0,
  'm03': 6574223500783771.0,
  'mu20': 3350067132875.9976,
  'mu11': -19852407.22685386,
  'mu02': 3436908928668.1587,
  'mu30': 474076306604.6929,
  'mu21': 68245533365.33664,
  'mu12': 40730787551.067085,
  'mu03': 439629269154.5414,
  'nu20': 0.00036484859466498276,
  'nu11': -2.162082904654043e-09,
  'nu02': 0.0003743063475685053,
  'nu30': 5.274389647449576e-09,
  'nu21': 7.592734115838284e-10,
  'nu12': 4.531549904495685e-10,
  'nu03': 4.891145230504086e-09})

In [157]:
X = int(moment ["m10"] / moment["m00"])
X

319

In [158]:
Y = int(moment ["m01"] / moment["m00"])
Y

323

In [159]:
c = cv2.circle(img, (X, Y), 15, (205, 114, 101), 1)
c

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [160]:
cv2.imshow("Center of the Image", img)

cv2.waitKey(0)

-1

In [169]:
# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-166-165cf89a4138> in <module>
# ----> 1 if c == img:
#       2     print(1)

# ValueError: The truth value of an array with more than one element is
# ambiguous.

# Use a.any() or a.all()

if c.all() == img.all():
    print('all block maches')

all block maches


In [170]:
# # img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\py.jpg')

# cv2.imshow("Center of the Image", img)

# cv2.waitKey(0)

-1

# Apply a mask for a colored image

### https://en.wikipedia.org/wiki/Circle_Hough_Transform

In [210]:
import cv2
import numpy as np

img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\fish.jpg')

cv2.imshow("Original Image", img)
cv2.waitKey(0)

-1

In [211]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

cv2.imshow("Gray Image", gray_img)
cv2.waitKey(0)

-1

In [213]:
medianBlurimg = cv2.medianBlur(gray_img, 3)

cv2.imshow("Median Blurimg Image", medianBlurimg)
cv2.waitKey(0)

-1

In [214]:
circles = cv2.HoughCircles(medianBlurimg, cv2.HOUGH_GRADIENT, 1, 20, param1=50, param2=50, minRadius=1, maxRadius=0)

cv2.imshow("Hough Circles Image", circles)
cv2.waitKey(0)

# i am facing problem in this cell...

error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\hough.cpp:1728: error: (-215:Assertion failed) !_image.empty() && _image.type() == CV_8UC1 && (_image.isMat() || _image.isUMat()) in function 'cv::HoughCircles'


In [208]:
circlesint16 = np.uint16(np.around(circles))

cv2.imshow("Circles_int16 Image", circlesint16)
cv2.waitKey(0)

NameError: name 'circles' is not defined

In [209]:
masking = np.full((img.shape[0], img.shape[1]),0,dtype=np.uint8)

for j in circles[0, :]:
    cv2.circle(masking, (j[0], j[1]), j[2], (255, 255, 255), -1)

NameError: name 'circles' is not defined

In [204]:
final_img = cv2.bitwise_or(img1, img1, masking=masking)
final_img

TypeError: 'masking' is an invalid keyword argument for bitwise_or()

In [228]:
# Eye Hough Circles open CV

import cv2
import numpy as np

## Definitions

def get_circle(img, minR, maxR, p1, p2):
    if len(img.shape)==3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    circles = cv2.HoughCircles(img, cv2.HOUGH_GRADIENT,1,20, param1=p1,param2=p2,minRadius=minR,maxRadius=maxR)
    circles = np.uint16(np.around(circles))

    #return the first circle
    return circles[0][0]

def print_img(img,x,y,w,h):
    if w!=0 and h!=0:
        cv2.imshow('detected circles',img[x:x+w,y:y+h])
        cv2.imwrite('app-1/1.jpg',img[x:x+w,y:y+h])
    else:
        cv2.imshow('detected circles',img)
        cv2.imwrite('app-1/1.jpg',img)
    cv2.waitKey(0)

    cv2.destroyAllWindows()

def reject_out(img, xc, yc, r):
    row = len(img)
    col = len(img[0])

    for x in range(0,row):
        for y in range(0, col):
            res = (x-xc)*(x-xc) + (y-yc)*(y-yc)
            if res > r*r :
                img[x][y] = 0

def reject_in(img, xc, yc, r):
    xs = xc-r
    ys = yc-r

    for x in range(xs,xs+2*r):
        for y in range(ys, ys+2*r):
            res = (x-xc)*(x-xc) + (y-yc)*(y-yc)
            if res < r*r :
                img[x][y] = 0

def extract_iris(img):
    cimg    = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    cord    = get_circle(cimg, 35, 0, 50, 40)
    # draw the outer circle
    cv2.circle(cimg,(cord[0],cord[1]),cord[2],(0,255,0),2)
    # draw the center of the circle
    cv2.circle(cimg,(cord[0],cord[1]),2,(0,0,255),3)


    h = 2*cord[2]
    w = 2*cord[2]
    x = cord[1]-cord[2]
    y = cord[0]-cord[2]
    nimg = img[x:x+w,y:y+h]

    reject_out(nimg, h/2, w/2, h/2)
    print_img(cimg,0,0,0,0)

    nimg = cv2.cvtColor(nimg, cv2.COLOR_GRAY2BGR)
    cord    = get_circle(nimg, 0, cord[2]-1, 50, 30)
    print (nimg[0:w][cord[0]])
    # draw the outer circle
    cv2.circle(nimg,(cord[0],cord[1]),cord[2],(0,255,0),2)
    # draw the center of the circle
    cv2.circle(nimg,(cord[0],cord[1]),2,(0,0,255),3)
    reject_in(nimg, cord[1], cord[0], cord[2])
    print_img(nimg,0,0,0,0)
    print (nimg[0:w][cord[0]])



img = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\eye.png', 0)
img = cv2.medianBlur(img,5)
extract_iris(img)

[[  0   0   0]
 [110 110 110]
 [104 104 104]
 [ 97  97  97]
 [ 96  96  96]
 [ 95  95  95]
 [ 94  94  94]
 [ 94  94  94]
 [ 94  94  94]
 [ 94  94  94]
 [ 95  95  95]
 [ 97  97  97]
 [ 97  97  97]
 [ 96  96  96]
 [ 96  96  96]
 [ 94  94  94]
 [ 94  94  94]
 [ 94  94  94]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 93  93  93]
 [ 91  91  91]
 [ 89  89  89]
 [ 89  89  89]
 [ 89  89  89]
 [ 89  89  89]
 [ 89  89  89]
 [ 89  89  89]
 [ 90  90  90]
 [ 89  89  89]
 [ 89  89  89]
 [ 85  85  85]
 [ 84  84  84]
 [ 79  79  79]
 [ 71  71  71]
 [ 55  55  55]
 [ 47  47  47]
 [ 44  44  44]
 [ 44  44  44]
 [ 43  43  43]
 [ 43  43  43]
 [ 42  42  42]
 [ 42  42  42]
 [ 42  42  42]
 [ 41  41  41]
 [ 41  41  41]
 [ 41  41  41]
 [ 41  41  41]
 [ 41  41  41]
 [ 41  41  41]
 [ 41  41  41]
 [ 40  40  40]
 [ 39  39  39]
 [ 39  39  39]
 [ 38  38  38]
 [ 38  38  38]
 [ 38  38  38]
 [ 38  38  38]
 [ 38  38 

# Extracting text from Image (OCR)

To extract text from an image, you can use Google Tesseract-OCR. You can download it from this link

## https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-3.05.02-20180621.exe

In [223]:
import pytesseract

pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract.exe'
text = pytesseract.image_to_string(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\pytext.png')
print(text)

LikeGeeks.c0m is a website
which contains articles about
Linux, programming, web
development, iOS, Python and
other tech tips.


In [251]:
import googletrans

type(googletrans.LANGUAGES)
googletrans.LANGUAGES

{'af': 'afrikaans',
 'sq': 'albanian',
 'am': 'amharic',
 'ar': 'arabic',
 'hy': 'armenian',
 'az': 'azerbaijani',
 'eu': 'basque',
 'be': 'belarusian',
 'bn': 'bengali',
 'bs': 'bosnian',
 'bg': 'bulgarian',
 'ca': 'catalan',
 'ceb': 'cebuano',
 'ny': 'chichewa',
 'zh-cn': 'chinese (simplified)',
 'zh-tw': 'chinese (traditional)',
 'co': 'corsican',
 'hr': 'croatian',
 'cs': 'czech',
 'da': 'danish',
 'nl': 'dutch',
 'en': 'english',
 'eo': 'esperanto',
 'et': 'estonian',
 'tl': 'filipino',
 'fi': 'finnish',
 'fr': 'french',
 'fy': 'frisian',
 'gl': 'galician',
 'ka': 'georgian',
 'de': 'german',
 'el': 'greek',
 'gu': 'gujarati',
 'ht': 'haitian creole',
 'ha': 'hausa',
 'haw': 'hawaiian',
 'iw': 'hebrew',
 'hi': 'hindi',
 'hmn': 'hmong',
 'hu': 'hungarian',
 'is': 'icelandic',
 'ig': 'igbo',
 'id': 'indonesian',
 'ga': 'irish',
 'it': 'italian',
 'ja': 'japanese',
 'jw': 'javanese',
 'kn': 'kannada',
 'kk': 'kazakh',
 'km': 'khmer',
 'ko': 'korean',
 'ku': 'kurdish (kurmanji)',
 'ky

In [290]:
import pytesseract
from PIL import Image
import pyttsx3
from googletrans import Translator

img = r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\status.png'
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract.exe'
result = pytesseract.image_to_string(img)

p = Translator() 
k = p.translate(result, dest='hi')

print(result)
print()
# print(k)

e = str(k)
h = e[33:-49]
print(h)

with open(r'C:\Users\Vicky Kumar\Desktop\Experiments\read and write in file\pytesseract.txt', mode ='w') as file:
    file.write(result)
#     file.write(h)

engine = pyttsx3.init() 
engine.say(k)
engine.runAndWait() 

Someone's mother has four
sons. North, South and East.
What is the name of the
fourth son. Private message
me the name of the fourth
son. If you lose, you have to
repost.

I lost to Pragya

किसी की मां चार है
बेटों। उत्तर, दक्षिण और पूर्वी।
का नाम क्या है
चौथा बेटा। निजी संदेश
मुझे चौथी का नाम
बेटा। आप खो देते हैं, आप के लिए है
repost।

मैं प्रज्ञा के लिए खो दिया


In [291]:
img, print(img)

C:\Users\Vicky Kumar\Pictures\Saved Pictures\status.png


('C:\\Users\\Vicky Kumar\\Pictures\\Saved Pictures\\status.png', None)

In [293]:
import os
import pytesseract
from PIL import Image
import pyttsx3
from googletrans import Translator

p = Translator()
engine = pyttsx3.init()
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files (x86)\Tesseract-OCR\tesseract.exe'

path = os.path.join('C:\\Users', os.getlogin(), 'Pictures', 'Saved Pictures')
if not os.path.exists(path):
    os.mkdir(path)

directory = os.listdir(path)
sno = 1
print()
for image in directory:
    print(sno, image)
    sno += 1
    
os.startfile(path)
more = '1'
while more is not '0':
    
    index = int(input('\nWhich Image index : ')) - 1
    file = os.path.join(path, directory[index])
    print('\nCURRENT Image... ' + directory[index])
    text = pytesseract.image_to_string(file)
    print('Text in Image...\n\n' + text)
    os.startfile(file)
    
    k = p.translate(text, dest='hi')
    print()
    e = str(k)
    trans = e[33:-49]
    print('Translated Text in Image...\n\n' + trans)
    
    engine.say(trans)
    engine.runAndWait()

    more = input('See another? (1/0) : ')
else:
    print('\nLook @ it...')


1 10-Median-Blur.png
2 Annotation 2020-03-14 101055.png
3 Annotation 2020-03-20 125751.png
4 Annotation 2020-03-20 181619.png
5 Annotation 2020-03-25 085757.png
6 Annotation 2020-03-26 193934.png
7 arya.png
8 car.png
9 desktop.ini
10 eye.png
11 f59f4d4e-aaf0-484d-addf-38181b67d1b7.jpg
12 fish.jpg
13 Helicopter.png
14 linkedin profile search.png
15 meme.jpg.png
16 mod.png
17 py.jpg
18 pytext.png
19 status.png
20 stuti boss liked file viewer.png
21 thali bajana.jpg
22 virus message.jpg

Which Image index : 19

CURRENT Image... status.png
Text in Image...

Someone's mother has four
sons. North, South and East.
What is the name of the
fourth son. Private message
me the name of the fourth
son. If you lose, you have to
repost.

I lost to Pragya

Translated Text in Image...

किसी की मां चार है
बेटों। उत्तर, दक्षिण और पूर्वी।
का नाम क्या है
चौथा बेटा। निजी संदेश
मुझे चौथी का नाम
बेटा। आप खो देते हैं, आप के लिए है
repost।

मैं प्रज्ञा के लिए खो दिया
See another? (1/0) : 0

Look @ it...


# Detect and correct text skew

In [230]:
# https://likegeeks.com/python-image-processing/