## I want to thank this website, which helped me to learn more about 'dlib' library...

# https://pysource.com/2019/03/25/pigs-nose-instagram-face-filter-opencv-with-python/

### DLib: Library for Machine Learning.

### Q). What is DLIB used for?

### Ans). Dlib is a modern C++ toolkit containing machine learning algorithms and tools for creating complex software in C++ to solve real world problems. It is used in both industry and academia in a wide range of domains including robotics, embedded devices, mobile phones, and large high performance computing environments

# Image_Processing.ipynb
# https://github.com/imvickykumar999/calender/blob/master/Image%20Processing.ipynb

In [186]:
import cv2, os
import numpy as np
import dlib
from math import hypot

# Loading Camera and Nose image and Creating mask
cap = cv2.VideoCapture(0)

nose_image = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\petnose.jpg')
_, frame = cap.read()

rows, cols, _ = frame.shape
nose_mask = np.zeros((rows, cols), np.uint8)

# Loading Face detector
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(r"C:\Users\Vicky Kumar\Downloads\shape_predictor_68_face_landmarks.dat")

while(cv2.waitKey(30) != ord('q')):
    _, frame = cap.read()
    nose_mask.fill(0)
    gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = detector(frame)
    for face in faces:
        landmarks = predictor(gray_frame, face)
        
        # Nose coordinates
        top_nose = (landmarks.part(29).x, landmarks.part(29).y)
        center_nose = (landmarks.part(30).x, landmarks.part(30).y)
        left_nose = (landmarks.part(31).x, landmarks.part(31).y)
        right_nose = (landmarks.part(35).x, landmarks.part(35).y)
        nose_width = int(hypot(left_nose[0] - right_nose[0],
                           left_nose[1] - right_nose[1]) * 1.7)
        nose_height = int(nose_width * 0.77)
        
        # New nose position
        top_left = (int(center_nose[0] - nose_width / 2),
                              int(center_nose[1] - nose_height / 2))
        bottom_right = (int(center_nose[0] + nose_width / 2),
                       int(center_nose[1] + nose_height / 2))

        # Adding the new nose
        nose_pig = cv2.resize(nose_image, (nose_width, nose_height))
        nose_pig_gray = cv2.cvtColor(nose_pig, cv2.COLOR_BGR2GRAY)
        _, nose_mask = cv2.threshold(nose_pig_gray, 25, 255, cv2.THRESH_BINARY_INV)
        nose_area = frame[top_left[1]: top_left[1] + nose_height,
                    top_left[0]: top_left[0] + nose_width]
        nose_area_no_nose = cv2.bitwise_and(nose_area, nose_area, mask=nose_mask)
        final_nose = cv2.add(nose_area_no_nose, nose_pig)
        frame[top_left[1]: top_left[1] + nose_height,
                    top_left[0]: top_left[0] + nose_width] = final_nose
        
#         cv2.imshow("Nose area", nose_area)
#         cv2.imshow("Nose pig", nose_pig)
#         cv2.imshow("final nose", final_nose)
    cv2.imshow("Frame", frame)
    
cap.release()
cv2.destroyAllWindows()

os.startfile(r'C:\Users\Vicky Kumar\Videos\Captures\filter.mp4') # post this video and Shape predictor 68 face landmarks photo...

In [197]:
x = (ord('q'), ord('A'), ord('a'), cv2.waitKey(30))
y = [4, 6.89, 'y', 'aim']

d  = dict(zip(x, y))

print('{}\t\t\t\t..... {}\n\n{}\t\t\t\t\t..... {}\n\n{} \t\t\t\t..... {}\n\n{} \t..... {}'
      .format(d, type(d), d.keys(), type(d.keys()), d.values(), type(d.keys()), d.items(), type(d.items())))

ord_ =  ord('A'), type(ord('A'))
ord_, type(ord_)

{113: 4, 65: 6.89, 97: 'y', -1: 'aim'}				..... <class 'dict'>

dict_keys([113, 65, 97, -1])					..... <class 'dict_keys'>

dict_values([4, 6.89, 'y', 'aim']) 				..... <class 'dict_keys'>

dict_items([(113, 4), (65, 6.89), (97, 'y'), (-1, 'aim')]) 	..... <class 'dict_items'>


((65, int), tuple)

In [198]:
cv2.waitKey(30), ord('q'), cv2.waitKey(30) != ord('q')

(-1, 113, True)

## >>> Learning Line by line...

In [2]:
import cv2

# ============================================================================

lst = str(cv2).split("'")[-2].split('\\')
location = ''

for i in range(len(lst)):
    location = location + lst[i] + '/'
    
location.split('.py')[0] + '.py'

# with open(location.split('.py')[0] + '.py', 'r') as f:
#     print(f.read())

'C://Users//Vicky Kumar//AppData//Roaming//Python//Python37//site-packages//cv2//cv2.cp37-win_amd64.py'

In [3]:
import numpy as np

# ======================================================================

lst = str(np).split("'")[-2].split('\\')
location = ''

for i in range(len(lst)):
    location = location + lst[i] + '/'
    
with open(location.split('.py')[0] + '.py', 'r') as f:
    print(f.read())

"""
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particul

In [265]:
import dlib

# ======================================================================

lst = str(dlib).split("'")[-2].split('\\')
location = ''

for i in range(len(lst)):
    location = location + lst[i] + '/'
    
location.split('.py')[0] + '.py'

# with open(location.split('.py')[0] + '.py', 'r') as f:
#     print(f.read())

'C://Users//Vicky Kumar//Anaconda3//lib//site-packages//dlib.cp37-win_amd64.py'

In [266]:
from math import hypot
import math
# ======================================================================

lst = str(math).split("'")[-2].split('\\')
location = ''

for i in range(len(lst)):
    location = location + lst[i] + '/'
    
location.split('.py')[0] + '.py'

# with open(location.split('.py')[0] + '.py', 'r') as f:
#     print(f.read())

'math/.py'

In [267]:
# Loading Camera and Nose image and Creating mask
cap = cv2.VideoCapture(0)
cap

<VideoCapture 00000200AF0913B0>

In [268]:
nose_image = cv2.imread(r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\petnose.jpg')
nose_image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [338]:
cv2.imshow("nose_image", nose_image)
cv2.waitKey(0)

-1

In [270]:
_, frame = cap.read()
_, frame

(True,
 array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8))

In [271]:
rows, cols, _ = frame.shape
rows, cols, _

(480, 640, 3)

In [255]:
nose_mask = np.zeros((rows, cols), np.uint8)
nose_mask

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [272]:
# Python Program illustrating 

# ...........numpy.zeros.............. method 

import numpy as geek 

b = geek.zeros(2, dtype = int) 
print("Matrix b : \n", b) 

a = geek.zeros((2, 2), dtype = int) 
print("\nMatrix a : \n", a) 

c = geek.zeros([3, 3]) # dtype = float (by default)
print("\nMatrix c : \n", c) 


Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [273]:
# Loading Face detector
detector = dlib.get_frontal_face_detector()
detector, type(0x226fb1326f0)

(<dlib.fhog_object_detector at 0x200af082ab0>, int)

In [274]:
predictor = dlib.shape_predictor(r"C:\Users\Vicky Kumar\Downloads\shape_predictor_68_face_landmarks.dat")
predictor, 0x226fb1323f0

(<dlib.shape_predictor at 0x200af082370>, 2366444348400)

In [275]:
# while(cv2.waitKey(30) != ord('q')):
cv2.waitKey(30) != ord('q')

True

In [276]:
_, frame = cap.read()
_, frame, type(frame)

(True,
 array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 numpy.ndarray)

In [277]:
cv2.imshow("frame", frame)
cv2.waitKey(0)

-1

In [279]:
m = nose_mask.fill(0)
type(m), nose_mask, type(nose_mask)

(NoneType,
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 numpy.ndarray)

In [280]:
# Python program explaining 
# numpy.ndarray.fill() function 
import numpy as geek 

a = geek.empty([3, 3]) 

# Initializing each element of the array 
# with 1 by using nested loops 
for i in range(3): 
	for j in range(3): 
		a[i][j] = '89.786'

print("a is : \n", a)	 


# now we are initializing each element 
# of the array with 1 using fill() function. 
a.fill(45.938) 

print("\nAfter using fill() a is : \n", a) 
	

a is : 
 [[89.786 89.786 89.786]
 [89.786 89.786 89.786]
 [89.786 89.786 89.786]]

After using fill() a is : 
 [[45.938 45.938 45.938]
 [45.938 45.938 45.938]
 [45.938 45.938 45.938]]


In [281]:
try:
    print(type(COLOR_BGR2GRAY))
    
except Exception as e:
    print(e)
    
cv2.COLOR_BGR2GRAY, type(cv2.COLOR_BGR2GRAY), type(cv2)

name 'COLOR_BGR2GRAY' is not defined


(6, int, module)

In [282]:
gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
gray_frame, type(gray_frame)

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 numpy.ndarray)

In [311]:
cv2.imshow("gray_frame", gray_frame)
cv2.waitKey(0)

-1

In [284]:
detector

In [285]:
faces = detector(frame)
faces, type(faces)

(rectangles[[(277, 211) (427, 360)]], dlib.rectangles)

In [286]:
predictor, 0x226fb152a70

(<dlib.shape_predictor at 0x200af082370>, 2366444481136)

In [287]:
for face in faces:
    landmarks = predictor(gray_frame, face)
#     print(landmarks)
    
landmarks, 0x226faad4db0

(<dlib.full_object_detection at 0x200af0992f0>, 2366437674416)

In [288]:
import os
faceial_points = r'C:\Users\Vicky Kumar\Pictures\Saved Pictures\facial_landmarks_68markup-768x619.jpg'
os.startfile(faceial_points) # post Shape predictor 68 face landmarks photo and a video...

print('.... x and y coordinates of <<< Shape predictor 68 face landmarks >>>', end = '\n\n')
print(' x   y')
print('-------')

for p in range(68):
    print(landmarks.part(p), landmarks.part(p).x, landmarks.part(p).y)
    
type(landmarks), type(landmarks.part(67)), type(landmarks.part(0).x)

.... x and y coordinates of <<< Shape predictor 68 face landmarks >>>

 x   y
-------
(289, 267) 289 267
(292, 282) 292 282
(297, 298) 297 298
(303, 313) 303 313
(311, 327) 311 327
(322, 338) 322 338
(337, 347) 337 347
(354, 353) 354 353
(372, 352) 372 352
(389, 346) 389 346
(401, 335) 401 335
(408, 322) 408 322
(414, 308) 414 308
(417, 293) 417 293
(418, 278) 418 278
(417, 264) 417 264
(415, 249) 415 249
(297, 256) 297 256
(303, 243) 303 243
(316, 236) 316 236
(331, 235) 331 235
(344, 239) 344 239
(360, 237) 360 237
(371, 230) 371 230
(384, 227) 384 227
(397, 229) 397 229
(406, 238) 406 238
(355, 253) 355 253
(357, 265) 357 265
(359, 276) 359 276
(361, 287) 361 287
(347, 297) 347 297
(354, 298) 354 298
(362, 298) 362 298
(369, 295) 369 295
(375, 292) 375 292
(312, 263) 312 263
(320, 257) 320 257
(329, 256) 329 256
(337, 261) 337 261
(329, 264) 329 264
(320, 266) 320 266
(371, 256) 371 256
(379, 250) 379 250
(388, 248) 388 248
(395, 251) 395 251
(390, 256) 390 256
(380, 257) 380 257
(3

(dlib.full_object_detection, dlib.point, int)

In [289]:
# Nose coordinates

top_nose = landmarks.part(29).x, landmarks.part(29).y
top_nose, type(top_nose)

((359, 276), tuple)

In [290]:
center_nose = (landmarks.part(30).x, landmarks.part(30).y)
center_nose, type(center_nose)

((361, 287), tuple)

In [291]:
left_nose = (landmarks.part(31).x, landmarks.part(31).y)
left_nose, left_nose[0], left_nose[1]

((347, 297), 347, 297)

In [292]:
right_nose = (landmarks.part(35).x, landmarks.part(35).y)

rn01 = right_nose[0], right_nose[1]

right_nose, rn01

((375, 292), (375, 292))

In [293]:
nose_width = int(hypot(left_nose[0] - right_nose[0], left_nose[1] - right_nose[1]) * 1.7)
nose_width

48

In [294]:
# Python3 program for hypot() function 

# Import the math module 
import math 

# Use of hypot fucntion 
print("hypot(3, 4) : ", math.hypot(3, 4)) 

# Neglects the negative sign 
print("hypot(-3, 4) : ", math.hypot(-3, 4)) 

print("hypot(6, 6) : ", math.hypot(6, 6)) 


hypot(3, 4) :  5.0
hypot(-3, 4) :  5.0
hypot(6, 6) :  8.48528137423857


In [295]:
# hypot() function ... to calculate hypotaneous of Triangle.

import numpy as np 

leg1 = [12, 3, 4, 6] 
print ("leg1 array : ", leg1) 


leg2 = [5, 4, 3, 8] 
print ("leg2 array : ", leg2) 

result = np.hypot(leg1, leg2) 
print("\nHypotenuse is as follows :") 
print(result) 


leg1 array :  [12, 3, 4, 6]
leg2 array :  [5, 4, 3, 8]

Hypotenuse is as follows :
[13.  5.  5. 10.]


In [296]:
nose_height = int(nose_width * 0.77) # fact : ratio
nose_height

36

In [297]:
# New nose position

top_left = (int(center_nose[0] - nose_width / 2), int(center_nose[1] - nose_height / 2))
top_left

(337, 269)

In [298]:
bottom_right = (int(center_nose[0] + nose_width / 2), int(center_nose[1] + nose_height / 2))
bottom_right

(385, 305)

In [346]:
# Adding the new nose

nose_pig = cv2.resize(nose_image, (nose_width, nose_height))
nose_pig, type(nose_pig)

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 numpy.ndarray)

In [347]:
cv2.imshow("nose_pig", nose_pig)
cv2.waitKey(0)

-1

In [304]:
nose_pig_gray = cv2.cvtColor(nose_pig, cv2.COLOR_BGR2GRAY)
nose_pig_gray, type(nose_pig_gray)

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 numpy.ndarray)

In [334]:
cv2.imshow("nose_pig_gray", nose_pig_gray)
cv2.waitKey(0)

-1

In [323]:
_, nose_mask = cv2.threshold(nose_pig_gray, 25, 255, cv2.THRESH_BINARY_INV)

_, nose_mask, type(nose_mask), cv2.threshold

(25.0,
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 numpy.ndarray,
 <function threshold>)

In [342]:
nose_area = frame[top_left[1]: top_left[1] + nose_height, top_left[0]: top_left[0] + nose_width]
nose_area, type(nose_area)

(array([[[77, 59, 57],
         [68, 53, 48],
         [61, 48, 45],
         ...,
         [85, 74, 81],
         [83, 72, 79],
         [79, 68, 73]],
 
        [[77, 59, 58],
         [66, 50, 49],
         [59, 45, 46],
         ...,
         [77, 70, 74],
         [76, 67, 72],
         [80, 72, 75]],
 
        [[74, 56, 55],
         [67, 51, 50],
         [63, 49, 50],
         ...,
         [77, 70, 74],
         [77, 68, 73],
         [80, 72, 75]],
 
        ...,
 
        [[56, 51, 55],
         [57, 52, 55],
         [59, 54, 57],
         ...,
         [68, 60, 61],
         [72, 65, 66],
         [65, 63, 63]],
 
        [[56, 51, 55],
         [56, 51, 54],
         [55, 50, 53],
         ...,
         [67, 59, 60],
         [70, 63, 64],
         [66, 64, 64]],
 
        [[49, 46, 49],
         [47, 47, 45],
         [47, 45, 43],
         ...,
         [75, 64, 61],
         [74, 64, 65],
         [80, 72, 75]]], dtype=uint8),
 numpy.ndarray)

In [343]:
cv2.imshow("nose_area", nose_area)
cv2.waitKey(0)

-1

## Arithmetic Operations on Images using OpenCV | Set-2 (Bitwise Operations on Binary Images)

### https://www.geeksforgeeks.org/arithmetic-operations-on-images-using-opencv-set-2-bitwise-operations-on-binary-images/

In [344]:
nose_area_no_nose = cv2.bitwise_and(nose_area, nose_area, mask=nose_mask)
nose_area_no_nose

array([[[77, 59, 57],
        [68, 53, 48],
        [61, 48, 45],
        ...,
        [85, 74, 81],
        [83, 72, 79],
        [79, 68, 73]],

       [[77, 59, 58],
        [66, 50, 49],
        [59, 45, 46],
        ...,
        [77, 70, 74],
        [76, 67, 72],
        [80, 72, 75]],

       [[74, 56, 55],
        [67, 51, 50],
        [63, 49, 50],
        ...,
        [77, 70, 74],
        [77, 68, 73],
        [80, 72, 75]],

       ...,

       [[56, 51, 55],
        [57, 52, 55],
        [59, 54, 57],
        ...,
        [68, 60, 61],
        [72, 65, 66],
        [65, 63, 63]],

       [[56, 51, 55],
        [56, 51, 54],
        [55, 50, 53],
        ...,
        [67, 59, 60],
        [70, 63, 64],
        [66, 64, 64]],

       [[49, 46, 49],
        [47, 47, 45],
        [47, 45, 43],
        ...,
        [75, 64, 61],
        [74, 64, 65],
        [80, 72, 75]]], dtype=uint8)

In [345]:
cv2.imshow("nose_area_no_nose", nose_area_no_nose)
cv2.waitKey(0)

-1

In [330]:
final_nose = cv2.add(nose_area_no_nose, nose_pig)
final_nose

array([[[77, 59, 57],
        [68, 53, 48],
        [61, 48, 45],
        ...,
        [85, 74, 81],
        [83, 72, 79],
        [79, 68, 73]],

       [[77, 59, 58],
        [66, 50, 49],
        [59, 45, 46],
        ...,
        [77, 70, 74],
        [76, 67, 72],
        [80, 72, 75]],

       [[74, 56, 55],
        [67, 51, 50],
        [63, 49, 50],
        ...,
        [77, 70, 74],
        [77, 68, 73],
        [80, 72, 75]],

       ...,

       [[56, 51, 55],
        [57, 52, 55],
        [59, 54, 57],
        ...,
        [68, 60, 61],
        [72, 65, 66],
        [65, 63, 63]],

       [[56, 51, 55],
        [56, 51, 54],
        [55, 50, 53],
        ...,
        [67, 59, 60],
        [70, 63, 64],
        [66, 64, 64]],

       [[49, 46, 49],
        [47, 47, 45],
        [47, 45, 43],
        ...,
        [75, 64, 61],
        [74, 64, 65],
        [80, 72, 75]]], dtype=uint8)

In [350]:
cv2.imshow("final_nose", final_nose)
cv2.waitKey(0)

-1

In [348]:
fn = frame[top_left[1]: top_left[1] + nose_height, top_left[0]: top_left[0] + nose_width] = final_nose
fn

array([[[77, 59, 57],
        [68, 53, 48],
        [61, 48, 45],
        ...,
        [85, 74, 81],
        [83, 72, 79],
        [79, 68, 73]],

       [[77, 59, 58],
        [66, 50, 49],
        [59, 45, 46],
        ...,
        [77, 70, 74],
        [76, 67, 72],
        [80, 72, 75]],

       [[74, 56, 55],
        [67, 51, 50],
        [63, 49, 50],
        ...,
        [77, 70, 74],
        [77, 68, 73],
        [80, 72, 75]],

       ...,

       [[56, 51, 55],
        [57, 52, 55],
        [59, 54, 57],
        ...,
        [68, 60, 61],
        [72, 65, 66],
        [65, 63, 63]],

       [[56, 51, 55],
        [56, 51, 54],
        [55, 50, 53],
        ...,
        [67, 59, 60],
        [70, 63, 64],
        [66, 64, 64]],

       [[49, 46, 49],
        [47, 47, 45],
        [47, 45, 43],
        ...,
        [75, 64, 61],
        [74, 64, 65],
        [80, 72, 75]]], dtype=uint8)

In [351]:
cv2.imshow("final_nose", fn)
cv2.waitKey(0)

-1

In [357]:
cv2.imshow("Nose area", nose_area)
cv2.imshow("Nose pig", nose_pig)
cv2.imshow("final nose", final_nose)
cv2.waitKey(0)

113

In [354]:
cv2.imshow("Frame", frame)
cv2.waitKey(0)

-1

In [312]:
a = cap.release()
b = cv2.destroyAllWindows()

a, b

(None, None)